// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oqsdpzjggeqgxwudcsfw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9xc2RwempnZ2VxZ3h3dWRjc2Z3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NzE0MjMsImV4cCI6MjA3MDI0NzQyM30.5dXdxSlRe_fO5Sy852jDC-TSXD0AN60BRxUo0znz3xk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});